### ISSUE TITLE
Add support for "let" binding

### ISSUE THREAD

**Issue by dbakuntsev** [aeremic/ko.lighter#1]
The highlighting ignores the opening virtual element for ["let" binding](https://knockoutjs.com/documentation/let-binding.html). Observed behavior:

![image](https://github.com/user-attachments/assets/845ffc33-2e32-42e1-b137-50be214dbbe9)

**Comment by aeremic** [comment]
resolved in 236deca3a1be9195425ddce4a59fa616d2e11b28
